
export const SET_ERROR = "SET_ERROR";

export const GET_ERROR = "GET_ERROR";

export const FETCH_START = `FETCH_START`;

export const FETCH_FAIL = "FETCH_FAIL";

export const FETCH_SUCCESS = "FETCH_SUCCESS"; 

export const FETCH_START_DEST_LIST = "FETCH_START_DEST_LIST";

export const FETCH_FAIL_DEST_LIST = "FETCH_FAIL_DEST_LIST";

export const FETCH_SUCCESS_DEST_LIST = "FETCH_SUCCESS_DEST_LIST"; 
