
export const SET_ERROR = "SET_ERROR";

export const ERROR_MONIT = "ERROR_MONIT";

export const SET_MAP_THEME = "SET_MAP_THEME"; 

export const FIND_DESTINATION = "FIND_DESTINATION";

export const DEST = "DEST";

export const DEST_LIST = "DEST_LIST";

export const COORDINATES = "COORDINATES";


export const FETCH_START = {
   DEST_LIST: "FETCH_START_DEST_LIST",
   DEST: `FETCH_START_DEST`,
   COORDINATES: "FETCH_START_COORDINATES"
};

export const FETCH_SUCCESS = {
   DEST_LIST: "FETCH_SUCCESS_DEST_LIST",
   DEST: `FETCH_SUCCESS_DEST`,
   COORDINATES: "FETCH_SUCCESS_COORDINATES"
};

export const FETCH_FAIL = {
   DEST_LIST: "FETCH_FAIL_DEST_LIST",
   DEST: `FETCH_FAIL_DEST`,
   COORDINATES: "FETCH_FAIL_COORDINATES"
};